### ISSUE TITLE
Segfault when running a rust test-executable on travis

### ISSUE THREAD

**Issue by vberger** [SimonKagstrom/kcov#105]
I'm currently running kcov via https://github.com/huonw/travis-cargo on one of my rust project on travis builds, and kcov fails and dies with (runned with `--verify --debug=15`)

```
PT signal 11 at 0x55555556b7cc for 8022
PT continuing 8022 with signal 11
PT stopped PID 8022 0x0000008b
PT terminating signal 11 at 0x55555556b7cc for 8022
PT continuing 8022 with signal 0
PT error for 8022: -1
Returning error
```

The full log is available on the travis build: https://travis-ci.org/metallirc/libmetallirc/builds/71119443

The troubling part is that I cannot reproduce this bug by running kcov on my computer, with the same nigthly precompiled version of the rust compiler. I get a segfault running kcov on the test executable, but adding the `--verify` flag fixes it on my computer. It does not fix it on travis (and it is a segfault at a different location).

I do not know if it is actually a problem from kcov or rustc, but I guess this is the most appropriate place to try and debug it.

**Comment by SimonKagstrom** [comment]
Thanks for the detailed report!

The (probable) reason --verify doesn't work in the Travis build is that the build environment doesn't have binutils-dev:

  https://travis-ci.org/metallirc/libmetallirc/builds/71119443#L583

and --verify works by disassembling the code and asserting that breakpoints are set on instruction boundaries. The disassembling needs libbfd, and as you might guess, this problem is basically x86-only. By installing binutils-dev before building kcov, you could get a working --verify at least (although it might require sudo for travis).

I guess I should print a big warning if --verify is used without binutils support.

Anyway, it would be interesting to know where the crash is - i.e., what instruction actually causes it. You can find that out by disassembling your binary and looking at 0x6b7cc. There are two problems I've seen so far: incorrectly generated debugging information, which I've seen with GCC 4.1, and SMP locking instructions (Issue #102).

**Comment by vberger** [comment]
Indeed, adding binutils-dev in the packages to install in my .travis.yml did fix the issue and made the whole thing run.

When I run it locally on my computer with `--verify`, it prints this message:

```
kcov: 1377 invalid breakpoints skipped in target/debug/metallirc-4addd24ae110fb39
```
If I run it without, it segfaults at adress 0x5555555652c4 and objdum gives me this content in the nearby assembly (if I didn't get it wrong):
```
00000000000652b0 <_ZN4iter30Map$LT$I$C$$u20$F$GT$.Iterator4next20h7285526875270533675E>:
   652b0:       64 48 3b 24 25 70 00    cmp    %fs:0x70,%rsp
   652b7:       00 00 
   652b9:       77 1a                   ja     652d5 <_ZN4iter30Map$LT$I$C$$u20$F$GT$.Iterator4next20h7285526875270533675E+0x25>
   652bb:       49 ba 38 00 00 00 00    movabs $0x38,%r10
   652c2:       00 00 00 
   652c5:       49 bb 00 00 00 00 00    movabs $0x0,%r11
   652cc:       00 00 00 
   652cf:       e8 98 32 ff ff          callq  5856c <__morestack>
   652d4:       c3                      retq   
   652d5:       55                      push   %rbp
   652d6:       48 89 e5                mov    %rsp,%rbp
   652d9:       48 83 ec 30             sub    $0x30,%rsp
```

**Comment by SimonKagstrom** [comment]
Great! Then it's an issue with the debugging information since the address is in the middle of an instruction. I don't know how rust generates debug info, but it might be worth issuing a bug report there (?).

It might also be possible to whitelist binutils-dev for Travis via a bug report.

**Comment by vberger** [comment]
Actually, I just had to add `binutils-dev`  in the `addons: apt: packages: ` section of my .travis.yml to get everything working, so its probably just an issue of documenting this somewhere.

About Rust, I think most of the debug information is generated by LLVM, but I guess I'll open an issue on Rust github repo, I don't know much about all this.

**Comment by SimonKagstrom** [comment]
OK! I guess it might be good to get --verify into travis-cargo upstream as well, since this issue will likely affect others as well?

**Comment by vberger** [comment]
Yep, I planned to get to it as well, once this was figured out

**Comment by SimonKagstrom** [comment]
c7ab88e adds a warning for --verify when binutils-dev isn't present. Closing since the issue itself has been resolved!
