### ISSUE TITLE
Build docker image with kcov from travis builds

### ISSUE THREAD

**Issue by SimonKagstrom** [SimonKagstrom/kcov#115]
For easier testing.

**Comment by brycefisher** [comment]
In my pet project, I ended up compiling kcov from source in `docker build` and pushing my image to the gitlab container register. However, I'd love to figure out how to make one (or more) docker builds triggered by merges to master in this repo, so that I and others could build containers on top of a docker image with kcov. I saw the seemingly unmaintained kcov on docker hub already, but it would be great to contribute an "official" image with your name on it, or a docker official image.

@SimonKagstrom Do you have a docker hub account? If so, docker hub can trigger builds from github webhooks. That would enable kcov builds to "just happen" automatically. I can contribute my existing Dockerfile. You (or something with privileged access to this repo and a docker hub account) would need follow these steps to setup the "automated builds":
https://docs.docker.com/docker-hub/builds/

Let me know if you're interested. I'm guessing we could easily get some Ubuntu flavored kcov docker images building automatically without too much effort.

**Comment by SimonKagstrom** [comment]
I do, username simonkagstrom. However, I've still got a lot to learn dockerwise, so expect slow progress :-)

But it would be good to have automatic builds of the git HEAD, as well as the latest release, if it is possible via Travis. I didn't really check the feasibility before creating this issue though!

**Comment by brycefisher** [comment]
Cool! I need to actually sleep tonight, but I'll try to investigate both options and report back here with my recommendations.

**Comment by SimonKagstrom** [comment]
Thanks for your work! But only do what's fun!

**Comment by Ragnaroek** [comment]
Hi,
since we already have a docker image on the docker hub for kcov (https://hub.docker.com/r/ragnaroek/kcov/) why not use this also for the head build?

I set up a new docker-hub with automatic build support (unfortunately auto build support cannot be added to the original kcov-hub-repo?). The repo is: https://hub.docker.com/r/ragnaroek/kcov_head/

To enable auto build you (Simon) would now have to install the webhook for triggering the build.
You need to do a POST to this URL https://registry.hub.docker.com/u/ragnaroek/kcov_head/trigger/<secret-trigger-token>

You can get the <secret-trigger-token> via private message if you are interested :)
Also I can add you as Collaborator with full admin rights to both docker repos, if you are interested :)

**Comment by SimonKagstrom** [comment]
Yes, using the existing build should be a good idea.

I'll show my ignorance here: How and where do I put the HTTP POST? Via curl in the Travis build script?

**Comment by Ragnaroek** [comment]
No, I think it would be better to use the webook feature of github.

Go to Settings > Webhooks in the repo account and paste the Payload URL is send you via private message to the field in the form. All other settings are ok with defaults.

That should be it. Next push in the repo should trigger the automatic build on the docker hub.

**Comment by Ragnaroek** [comment]
Apparently there is no private message feature on github :)

I send you an email with the link and token to you private email-account mentioned on your github profile page.

**Comment by SimonKagstrom** [comment]
Thanks to both docker masters!

I've setup the webhook and pushed a commit, so let's see what happens. Right now, I think there is a regression in kcov though, but I guess that goes with using the latest git HEAD of any project.

I'll close if it appears to work!

**Comment by Ragnaroek** [comment]
Can confirm that it works. I pulled the build image und run kcov --version on it. It gives me
kcov v33 :)

We now have to docker builds:
kcov_head
and
kcov

ragnaroek/kcov_head will only have the 'latest' tag with the latest tag. Offical builds with stable
version will always be on ragnaroek/kcov and updated with every release.

I will update the readme on the docker-repo with this information.

**Comment by Ragnaroek** [comment]
Maybe you could also update the readme of kcov with a link to the docker-hub images.
I think docker images are appealing for everyone that wants to use kcov but does not wan't to build it on their own?

**Comment by SimonKagstrom** [comment]
Yes, absolutely! It just didn't occur to me to do that, but it makes a lot of sense.

I'll update the README and close this issue after that.

**Comment by SimonKagstrom** [comment]
Documentation fixed with ec18565, thanks for your work!
