### ISSUE TITLE
kcov segfaults (SIGSEGV) on rust binaries in docker container

### ISSUE THREAD

**Issue by brycefisher** [SimonKagstrom/kcov#172]
### Steps to repro:

 * Install docker on your system: [linux](https://docs.docker.com/engine/installation/linux) or [mac](https://docs.docker.com/docker-for-mac/)
 * `docker pull ragnaroek/kcov:v31`
 * install rust: `curl https://sh.rustup.rs -sSf | sh`
 * create a rust helloworld binary: `cargo new --bin helloworld && cd helloworld && cargo build`
 * Run kcov from the container against helloworld binary: 

```bash
helloworld $ docker run \
  --rm \
   -it \
   --security-opt seccomp=unconfined \
   -v "$(pwd):/app" \
   ragnaroek/kcov:v31 /tmp/kcov /app/target/debug/helloworld
```
### Result:

> kcov: Process exited with signal 11 (SIGSEGV) at 0x55555556c18e

### Notes:

Kcov seems to work fine when run directly from my machine. I've also been able to reproduce this issue against the current head of master inside a docker container. I should note that in both cases I've compiled kcov inside the docker build process.

This issue seems suspiciously similar to https://github.com/SimonKagstrom/kcov/issues/124. The difference is that my binary is compiled rust, and the other issues seems to be cpp / clang.

### (Redacted) Docker / System Info

> Server Version: 1.12.3
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
>  Network: host null bridge overlay
> Runtimes: runc
> Default Runtime: runc
> Security Options: apparmor seccomp
> Kernel Version: 4.8.0-30-generic
> Operating System: Ubuntu 16.10
> Architecture: x86_64
> Total Memory: 15.59 GiB
> Debug Mode (client): false
> Debug Mode (server): false
> WARNING: No swap limit support

**Comment by brycefisher** [comment]
As soon as I posted this, I realized that the problem was I needed to include the `--verify` flag. For some rust binaries seem to segfault without this flag...

**Comment by brycefisher** [comment]
Also found this issue which is *exactly* the same:
https://github.com/SimonKagstrom/kcov/issues/153

It seems that in my docker container, kcov wasn't compiled with binutils-dev (libbfd), and so `--verify` doesn't work. The public docker image at `ragnaroek/kcov:v31` _is_ compiled with binutils-dev.

**Comment by SimonKagstrom** [comment]
Yes, it's a known issue. The DWARF debug information maps file/line pairs into an address which points into the middle of an instruction (probably only possible on x86), and setting a breakpoint there will simply create an invalid or otherwise broken instruction.

You will either get a SIGILL, in which case kcov prints some helpful hints about --verify, or a SIGSEGV if the instruction is valid, but makes the code break. kcov doesn't print helpful messages in that case, but perhaps it should.

I guess the worst situation is if the instruction is valid and doesn't affect execution very much - so that you can get a misbehaving program, but no crash!

**Comment by brycefisher** [comment]
So weird! Seems DWARF support is being [discussed](https://github.com/rust-lang/rust/issues/37504) by the rust compiler team.

**Comment by SimonKagstrom** [comment]
I think the Rust-specific issue is this:

  https://github.com/rust-lang/rust/issues/27324

but this also exists for C/C++ etc (seemingly often in system headers). One thing I often do anyway is to limit the coverage collection via --include-pattern=, since I'm not interested in /usr/include coverage anyway. For kcov itself, this fixes the crashes without having to use --verify, but this is obviously application-specific.
