### ISSUE TITLE
AArch64 support

### ISSUE THREAD

**Issue by NoctuaNivalis** [SimonKagstrom/kcov#178]
Somewhere in between v31 and v33, support for AArch64 seems to have been dropped. Below is the compilation error:

```
[  6%] Building C object src/CMakeFiles/kcov_sowrapper.dir/solib-parser/lib.c.o
/builddir/kcov-32/src/solib-parser/lib.c: In function 'force_breakpoint':
/builddir/kcov-32/src/solib-parser/lib.c:95:3: error: #error Unsupported architecture
 # error Unsupported architecture
```

Even though this method was included in v31, it did compile. I suspect it wasn't used before.

**Comment by SimonKagstrom** [comment]
Well, AArch64 hasn't really been supported ever, but might perhaps have worked in the same way as ARM. However, looking at the git log for lib.c, it hasn't been changed since v26, so I think it's strange that there is a difference compared to v31.

Anyway, I can add a check for AArch64 blindly (after looking at https://github.com/scottt/debugbreak/blob/master/debugbreak.h), but I can't really test it myself. Stay tuned for a commit soonish though :-)

**Comment by SimonKagstrom** [comment]
Implemented, but untested. If you have the time, feel free to test!

**Comment by NoctuaNivalis** [comment]
Will test, thanks for the quick respons (I probably won't even be that fast testing it).

**Comment by SimonKagstrom** [comment]
Thanks! With luck it will compile, but I would be very surprised if it actually works in the first iteration.

**Comment by NoctuaNivalis** [comment]
```
src/engines/ptrace.cc:331:28: error: 'PTRACE_GETREGS' was not declared in this scope
   ptrace((__ptrace_request)PTRACE_GETREGS, m_activeChild, 0, &regs);
                            ^~~~~~~~~~~~~~
src/engines/ptrace.cc:335:28: error: 'PTRACE_SETREGS' was not declared in this scope
   ptrace((__ptrace_request)PTRACE_SETREGS, m_activeChild, 0, &regs);
                            ^~~~~~~~~~~~~~
```
Doesn't compile. I'll try to send a compiling patch soon, and in the mean time find someone to really test this (I'm just cross-compiling for my distro).
