### ISSUE TITLE
full system instrument

### ISSUE THREAD

**Issue by mcgrady1** [SimonKagstrom/kcov#202]
Hi,

When i used kcov-system to do full system instrument for my binary, it printed:

kcov: error: key system-mode-read-results-file not found, so whats the problem?

Thanks!

**Comment by SimonKagstrom** [comment]
Well, the system-mode stuff is still quite a bit work-in-progress, so don't expect it to work reliably until after next release. Also, it requires a Dyninst installation as of now (will probably go away). Do you have dyninst installed?

With dyninst, it builds a kcov-system binary, which is needed to instrument and collect system-mode coverage.

**Comment by mcgrady1** [comment]
yes, i built dyninst and generated the kcov-system

**Comment by SimonKagstrom** [comment]
Well, you have some documentation here:

https://github.com/SimonKagstrom/kcov/blob/master/doc/full-system-instrumentation.md

although it will probably only work for simpler cases. I think I need to rethink the current approach since it has performance and functionality issues, but more on that later.

**Comment by mcgrady1** [comment]
thanks, i have seen the document before, and i think it doesn't work for my demo binary

**Comment by SimonKagstrom** [comment]
I'm closing this since I've rewritten the full system instrumentation from scratch, without dyninst. It's still quite lightly tested, so likely hides some bugs.
