### ISSUE TITLE
where do bash-helper.sh and bash-helper-debug-trap.sh come from

### ISSUE THREAD

**Issue by YvesZHI** [SimonKagstrom/kcov#228]
I have a simple bash script named `1.sh` as below:<br>
```
#!bin/sh
echo NOTHING
```

Then I execute: `kcov report 1.sh` to get the result:
![default](https://user-images.githubusercontent.com/27804279/34592665-beb2fc7e-f200-11e7-8893-ebaa2fbb78bd.PNG)

I don't know why it is 25%, instead of 100%. I've found that there were two new sh files, bash-helper.sh and bash-helper-debug-trap.sh, coming out.<br>
Where do they come from? Can I simply get a 100% for my `1.sh`?

**Comment by SimonKagstrom** [comment]
Well, it's a bug, and it's caused by a combination of things (which I haven't considered):

1. kcov tries to find even those shell scripts which aren't executed and include in the report. This is done in order to catch files which are included in some code paths, but would not be visible otherwise. If this is not wanted, you can turn it off with ```--bash-dont-parse-binary-dir```

2. kcov uses a few generated helper scripts to setup the environment (especially with ```---bash-method=DEBUG```. These are the extra files you see in the output.

3. You're placing the report in a subdirectory of the script with your test program, and this in turn causes kcov to (by point 1) look for extra scripts to include in the report - causing it to find it's own generated scripts.


So as a workaround (recommended in general), place the output outside of the script directory. However, kcov itself should also ignore the generated output files via their names. I'll look at that (well, unless you beat me to it and send a pull-request!).

**Comment by YvesZHI** [comment]
Great explanation.

Placing the output outside of the directory is fine by me   :)
