### ISSUE TITLE
Kcov merge with include-pattern and exclude-pattern

### ISSUE THREAD

**Issue by newuser-123** [SimonKagstrom/kcov#259]
I have kcov coverage details for multiple tests, but it has several others files included as well. Now, I want to merge all coverage data but with include-pattern or exclude-pattern. Does it work at this stage ? or it needs to be given at kcov invocation only?

I am unable to use patterns as of now.

**Comment by SimonKagstrom** [comment]
So you use `kcov --merge <out-dir> <to-merge1> <to-merge2>` or do you specify the same output directory for multiple runs?

Anyway, it doesn't currently work with `kcov --merge` since the merge reporter gets run with a "basic filter", see https://github.com/SimonKagstrom/kcov/blob/master/src/main.cc#L161 . I can't test right now, but I would guess passing the "non-basic" filter to it would give the behavior you seek.

**Comment by newuser-123** [comment]
Thanks Simon for the prompt reply. However, I am not facing any issues with --merge, it works well for me.
The real issue is when I want to include only particular files ( e.g. files with XYZ string in the names ) in the report and exclude all rest files. I was wondering if there are any options to do that at the time of kcov --merge .

Thanks in advance!

**Comment by SimonKagstrom** [comment]
No, it doesn't work since the merge-mode uses the "basic" filter, which ignores `--include-pattern` etc. However, I've pushed a fix, a760270, that should resolve this.
