### ISSUE TITLE
Feature Request: Provide binary releases

### ISSUE THREAD

**Issue by konstin** [SimonKagstrom/kcov#289]
Binary releases of kcov would be really useful. This would simplify ci setups with kcov from downloading, building and optionally caching kcov to just downloading and maybe unzipping a file. One option would e.g. be using [travis ci's github releases deploy](https://docs.travis-ci.com/user/deployment/releases/) with the existing ci setup.

**Comment by SimonKagstrom** [comment]
OK, I didn't know about Travis deploy releases.

One issue with this is library dependencies though. For binary releases, I'd like to ship static binaries. However, due to #134, it's currently  not possible to build static binaries. The problem is one of the dependent libraries, although I don't really remember which one it was.

An alternative is to use one of the docker images which are built for kcov on docker.io.

**Comment by konstin** [comment]
Even if they aren't really static binaries, it would still be really useful to have binaries.

I tried to figure out which libraries weren't statically linked, however I failed to compile with the static option:

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/installed -DKCOV_STATIC_BUILD=On
make -j 4
``` 

Leads to:

```
[ 98%] Linking CXX executable kcov
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(pthread_create.o): In Funktion »allocate_stack«:
/build/glibc-OTsEL5/glibc-2.27/nptl/allocatestack.c:526: Warnung: undefinierter Verweis auf »_dl_stack_flags«
/build/glibc-OTsEL5/glibc-2.27/nptl/allocatestack.c:652: Warnung: undefinierter Verweis auf »_dl_stack_flags«
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(elision-lock.o): In Funktion »do_set_elision_enable«:
/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/x86/elision-conf.c:67: Warnung: undefinierter Verweis auf »_dl_x86_cpu_features«
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In Funktion »__pthread_initialize_minimal_internal«:
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:294: Warnung: undefinierter Verweis auf »_dl_cpuclock_offset«
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:429: Warnung: undefinierter Verweis auf »_dl_pagesize«
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:438: Warnung: undefinierter Verweis auf »_dl_pagesize«
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:454: Warnung: undefinierter Verweis auf »_dl_init_static_tls«
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:456: Warnung: undefinierter Verweis auf »_dl_wait_lookup_done«
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.a(nptl-init.o): In Funktion »__pthread_get_minstack«:
/build/glibc-OTsEL5/glibc-2.27/nptl/nptl-init.c:475: Warnung: undefinierter Verweis auf »_dl_pagesize«
collect2: error: ld returned 1 exit status
src/CMakeFiles/kcov.dir/build.make:1187: recipe for target 'src/kcov' failed
make[2]: *** [src/kcov] Error 1
CMakeFiles/Makefile2:207: recipe for target 'src/CMakeFiles/kcov.dir/all' failed
make[1]: *** [src/CMakeFiles/kcov.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

[According to stackoverflow](https://stackoverflow.com/a/5761201/3549270) that error happens because you can't link libpthread statically while linking libc dynamically, but I don't know enough about cmake to fix that.

**Comment by SimonKagstrom** [comment]
Hmmm.. I think these are possible to work around, but if I remember correctly the real issue was with libbfd.

Anyway, I suppose it would be possible to build a binary release via travis, although it would come with some caveats when running on different systems. The docker images at least solve that issue.

**Comment by brycefisher** [comment]
Wanted to second this request. My main motivation is to speed up CI pipeline, so even if there were some extra setup steps, I would welcome that over downloading and compiling kcov on the regular since it would likely save me 45s per CI run.

**Comment by l3laze** [comment]
Also interested in this. I've started the process of automating build & release with GitHub Actions in my fork, but I'm not into C/C++ at all so cross-compiling tutorials are proving very difficult and have failed. Going to give it a shot again soon, though.

**Comment by SimonKagstrom** [comment]
Thanks for looking into this @l3laze!

**Comment by l3laze** [comment]
No problem :smile: I've really appreciated being able to use this project and it would be pretty cool to give back by contributing, especially since it's way out of my league. I also just started using GitHub Actions for one of my own projects as it didn't run properly on Travis-CI, and I generally enjoy automating CI/CD stuff like this though it takes a lot of trial and especially error.


I managed to get armhf cross-compiling from amd64 using https://github.com/uraimo/run-on-arch-action, but it takes 10+ minutes while the x64 native build only takes about 2 minutes. Lol. So, now I'm going to try to setup to use a build matrix to run jobs on all platforms at once. I'm doing this from my phone so it's 100% remote as all I can do locally is build for armhf and edit the ci.yml workflow file. I'm also starting a (sadly non-dev) job tonight and won't have as much time to code.


It seems like it may be possible to use ccache and/or Ninja to help speed up build times, but I need to get matrix builds working before I'll try ccache and IDK if Ninja is too complex (for me) to setup. Probably going to nuke what I have, re-fork, and restart as it's gotten very ugly and broken. I may now know more about using C/C++ build tools than using the language itself =))


The working cross-build + release workflow was as follows below. Note the trailing space at the end of "files", which seems to be required for it to find the last space-separated entry and is likely a bug in the action. Using `apt-mark hold` on some packages -- especially PHP -- helped cut build time down and still allows using `apt-get upgrade -y` to run the latest tools.


It is setup to overwrite "latest" each time it's run, which is set to be every push on the master branch but can easily be changed to tags only. The value of `secrets.GITHUB_TOKEN` is somehow generated magically by GH Actions and we don't have to worry.


```yml
name: CI
on:
  push:
    branches:
      - "master"
jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: uraimo/run-on-arch-action@v1.0.9
      with:
        architecture: armv7
        distribution: ubuntu18.04
        run: |
          apt-get update
          apt-mark hold php* google* dotnet* ansible kubectl libobjc* libpq* libidn* postgresql* python-samba python3-httplib2 samba* moby-containerd >/dev/null
          apt-get upgrade -y
          apt-get install -y binutils-dev libcurl4-openssl-dev libdw-dev libiberty-dev gcc g++ make cmake libssl-dev git python python3
          export PATH="${PATH}:${HOME}/kcov/bin"
          tar xzf master.tar.gz
          cd kcov-master
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. || exit 64
          make || exit 64
          make install || exit 64
          cd ../..
          rm -rf kcov-master
          tar czf kcov-armhf.tar.gz /usr/local/bin/kcov* /usr/local/share/doc/kcov/* /usr/local/share/man/man1/kcov.1

    - name: Build and package for x64
      run: |
        sudo apt-get update
        sudo apt-mark hold php* google* dotnet* ansible kubectl libobjc* libpq* libidn* postgresql* python-samba python3-httplib2 samba* moby-containerd >/dev/null
        sudo apt-get upgrade -y
        sudo apt-get install -y binutils-dev libcurl4-openssl-dev libdw-dev libiberty-dev gcc g++ make cmake libssl-dev git python python3
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
        export PATH="${PATH}:${HOME}/kcov/bin"
        tar xzf master.tar.gz
        cd kcov-master
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
        make
        sudo make install
        cd ../..
        rm -rf kcov-master
        tar czf kcov-x64.tar.gz /usr/local/bin/kcov* /usr/local/share/doc/kcov/* /usr/local/share/man/man1/kcov.1

    - name: Create/update "latest" release
      uses: meeDamian/github-release@v2.0.3
      with:
        tag: latest
        allow_override: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: kcov-x64.tar.gz kcov-armhf.tar.gz 

```

**Comment by SimonKagstrom** [comment]
Cool!

I hadn't realised that travis-ci now supports ARM testing as well. The ARM (and PowerPC) are not auto tested, so it's quite possible that they are broken.

Anyway, thanks a lot for looking into this, and feel free to send a pull request when you're happy with your fixes.

**Comment by l3laze** [comment]
Started over this morning and it's [working really well](https://github.com/l3laze/kcov/actions/runs/214247723) so far. Have a matrix building for native (amd64) + chroot on native (i386) + uraimo/run-on-arch-action (armv7, aarch64, ppc64le), and `readelf -h` to manually confirm they were built for the proper Class + Machine. It doesn't release yet, but that should be relatively reasonable.


What would it take to implement testing? Looking at travis/Makefile it seems like it would be way too crazy.

**Comment by SimonKagstrom** [comment]
Very nice!

I'm not sure how the Aarch64 etc stuff on travis works these days, but with some luck, it should build and run the regular tests as for other architectures. Anyway, let's not contaminate this particular improvement with that - binary releases are really a separate issue and a great improvement by itself.

**Comment by l3laze** [comment]
[It could use a code review](https://github.com/SimonKagstrom/kcov/pull/334). In tests it's working as expected, and I included an oversimplified test to make sure the executables are actually working too, but it isn't really necessary.

**Comment by SimonKagstrom** [comment]
I'm not familiar enough with the travis stuff to really give a good review, unfortunately. Merging anyway, and I think the tests might be a bit too tied to particular platforms to work well anywhere (this was the case for the FreeBSD port).

**Comment by l3laze** [comment]
Alright. It will only build releases for pushed tags, but I didn't get Mac builds working yet as there's *a lot* of problems there. I will try to work on that though. Thank you for letting me be a part of this! My most important programming work yet, as far as I'm concerned :)

**Comment by SimonKagstrom** [comment]
Yes, the Mac builds are broken in travis as well. Something has been updated in the underlying environment which breaks it, so that's a separate problems. Builds fine on my Mac though, so it's nothing fundamental.
