### ISSUE TITLE
Kcov miss-reports / eronate data

### ISSUE THREAD

**Issue by abanu-ms** [SimonKagstrom/kcov#351]
I've just installed kcov to get some code coverage data for a C++ binary, but it is looking pretty odd. I should say from the start that the binary in discussion is a daemon. The daemon is started via kcov at the beginning of the test session, and killed at the end. After running the UTs and taking a look at the coverage, there are some lines that should clearly be hit, but they don't look like they are, as the following:
![image](https://user-images.githubusercontent.com/74403209/104015719-b73f9b80-51bd-11eb-9453-a2b4417118fa.png)

I ran kcov with --debug=15 as well, to see if there's something odd going on. In the debug traces, it shows the line is being hit, but in the HTML it doesn't report like it is (also I don't quite understand why lines 34 and 35 are reported at the same address):
![image](https://user-images.githubusercontent.com/74403209/104015998-21584080-51be-11eb-832d-d57104e6557e.png)
![image](https://user-images.githubusercontent.com/74403209/104016084-3c2ab500-51be-11eb-848b-c27b9d04b4b0.png)

Also, another thing is that I do not really understand how the hit counter on the left-hand works. For example, I have a constructor which I know for a fact it should be hit more than once, but it looks like it was hit only once:
![image](https://user-images.githubusercontent.com/74403209/104016168-69776300-51be-11eb-80b8-6e2bef913e55.png)

However, it's destructor is called multiple times, and I don't quite get what 12/28 means in this case:
![image](https://user-images.githubusercontent.com/74403209/104016198-857b0480-51be-11eb-8673-3af72da0d33b.png)

There are multiple examples like this in the coverage data I gathered, I only chose these to give as example. Also, I remarked that running kcov with a more generic include-pattern can provide different coverage data/percentage for the same file.

The kcov command I used for this is looking like this:
` kcov --include-pattern=/nhgorch --replace-src-path=./orchagent/./orchagent:/opt/sonic-swss/orchagent /opt/sonic-swss/codecov/$(date +%s) /usr/bin/orchagent ${ORCHAGENT_ARGS}`

Maybe I'm not understanding just right how kcov is supposed to work, but I didn't quite manage to find any useful info in the issues I looked at. Is it there something that I'm doing/understanding wrong?

**Comment by SimonKagstrom** [comment]
Is your binary built with optimization? Then you typically get strange results.


Kcov works in the same way as a debugger, via breakpoints, and the hit count simply specifies if a line was hit one time. After that the breakpoint is disabled because it would otherwise cause an immense slowdown of execution. And in the same way as when running a debugger on an optimized binary, you can sometimes get strange sequences and results.

When there's 1/4 or so, it means that there are 4 debug info entries on the same line, but only one of them has been hit. A typical example of this could be e.g.,

  if (a || b)

which could generate two entries, one for the a comparison and one for the b comparison.

For the destructor you have above, it might either be because it's in a header file and referenced from multiple implementations, or simply because C++ does a lot of things under the hood, which might generates debug entries but which isn't easily visible in the code.

I can't really say why the 34/35 line entries are like that, that sounds a bit strange. One of them is only the variable  declaration though, so perhaps it's some sort of initialization that the compiler squashes with the assignment on line 35.

**Comment by abanu-ms** [comment]
Indeed, the debian rule for building the package seems to use -O2 when building the code. I thought it might be due to compiler optimizations, but I couldn't be really sure.

Thanks for explaining how the breakpoints are used and everything else. Those hit "counters" make sense now.

I'll try figuring out a way to build this without any compiler optimizations, and I'll close this ticket as it doesn't seem to be a kcov problem. Thanks again!
