### ISSUE TITLE
Process exited with signal 11 (SIGSEGV) at 0x55555555bcfc

### ISSUE THREAD

**Issue by rossmuir** [SimonKagstrom/kcov#82]
Running kcov against rust code with

```kcov target/kcov target/debug/self_encryption-*```

I am getting this returned?

```kcov: Process exited with signal 11 (SIGSEGV) at 0x55555555bcfc```

I have ran with `--debug=15` and you can find the output file here > https://drive.google.com/file/d/0B104YW6-k2p0YkR3WmV1R3lBMEk/view?usp=sharing

**Comment by SimonKagstrom** [comment]
Can you disassemble the program and see what is at address 0x555...bcfc (I guess it will show up as 0xbcfc in the executable)?

kcov hasn't setup a breakpoint for 0xbcfc, but there are breakpoints for 0xbcfa and 0xbcff. There is a gcc bug which generates DWARF address which are not aligned on instruction boundaries, and this is reported as kcov Issue #18. Perhaps something similar has happened here? If that is the case, there won't be any instruction at 0xbcfc, and this address will instead be somewhere in the middle of an instruction (all this is assuming  you're executing on i386 or x86_64).

Or otherwise it's some other issue!

**Comment by SirDoctors** [comment]
I'm noticing this same error, however I can get different SIGSERV's specifying different files.
```
doc@lappy $ kcov target/cov target/debug/alchemist_server
kcov: Process exited with signal 11 (SIGSEGV) at 0x5555559d9eae
doc@lappy $ kcov target/cov target/debug/alchemist_server-3cd12d29469bca5e
kcov: Process exited with signal 11 (SIGSEGV) at 0x55555556274b
doc@lappy $ kcov target/cov target/debug/alchemist_server-c48ffd415142052d
kcov: Process exited with signal 11 (SIGSEGV) at 0x55555556274b
doc@labby $ kcov target/cov target/debug/alchemist_server*
kcov: Process exited with signal 11 (SIGSEGV) at 0x5555559d9eae
```

**Comment by SimonKagstrom** [comment]
Try with --verify, if you built with binutils-dev. Kcov will give hints on
programs crashing with sigill, but sigsegv is a bit too common ;-)

**Comment by SirDoctors** [comment]
hmm it seems that my problem is solved by passing --verify, have no more issues with that passed.

**Comment by SimonKagstrom** [comment]
Yes, the reason is explained in one of the comment above: It´s a bug in the DWARF generation, and --verify simply disassembles the program before setting breakpoints to make sure that breakpoints are actually set on the start of instruction and not in the middle of an instruction. This would typically gives an invalid instruction and a SIGILL crash, but in some cases (like yours), the actual instruction is valid, but obviously doesnt work as intended and causes a crash instead.

Good that it resolved your problem!
